overrides:
  '@mailerlite/mailerlite-nodejs>axios': ^1.15.0
  axios>follow-redirects: ^1.16.0
  formik>lodash: ^4.18.0
  formik>lodash-es: ^4.18.0
  cypress>lodash: ^4.18.0
  minimatch@3.1.5>brace-expansion: 1.1.13
  minimatch@9.0.9>brace-expansion: 2.0.3

allowBuilds:
  '@tsparticles/engine': true
  cypress: true
  esbuild: true
  sharp: true
  unrs-resolver: true
