import type { Metadata } from 'next';
import localFont from 'next/font/local';

import './globals.css';
import { Footer } from '@components/footer/Footer';
import { Source_Sans_3 } from 'next/font/google';

const montserratAlt1 = localFont({
    src: [
        {
            path: '../fonts/otf/MontserratAlt1-Regular.otf',
            style: 'normal'
        },
        {
            path: '../fonts/otf/MontserratAlt1-Black.otf',
            style: 'italic'
        },
        {
            path: '../fonts/otf/MontserratAlt1-Bold.otf',
            weight: '700',
            style: 'bold'
        },
        {
            path: '../fonts/otf/MontserratAlt1-SemiBold.otf',
            style: 'semibold'
        },
        {
            path: '../fonts/otf/MontserratAlt1-ExtraBold.otf',
            weight: '700',
            style: 'extrabold'
        },
        {
            path: '../fonts/otf/MontserratAlt1-Thin.otf',
            style: 'thin'
        },
        {
            path: '../fonts/otf/MontserratAlt1-Medium.otf',
            style: 'medium'
        },
        {
            path: '../fonts/otf/MontserratAlt1-Light.otf',
            style: 'light'
        },
        {
            path: '../fonts/otf/MontserratAlt1-ExtraLight.otf',
            style: 'extralight'
        }
    ],
    variable: '--font-family-montserrat-alt1'
});

const sourceSans = Source_Sans_3({
    subsets: ['latin'],
    variable: '--font-family-source-sans'
});

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app'
};

const RootLayout = ({ children }: Readonly<{ children: React.ReactNode; }>) => (
    <html lang="en" className={`${montserratAlt1.variable} ${sourceSans.variable}`}>
        <body>
            {children}
            <Footer />
        </body>
    </html>
);

export default RootLayout;
