version: 2
updates:
  # Enable version updates for the pnpm-managed Node.js project
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: monthly
      timezone: 'America/Los_Angeles'
